# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
image: node:16-bullseye-slim
stages:
- Build
- Deploy

.deploy:
  stage: Deploy
  needs:
  - Node
  rules:
  - if:
      $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH &&
        $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  before_script:
  - npm config --global set \
      access=public \
      registry="https://${REGISTRY}" \
      "//${REGISTRY}/:_authToken"='${TOKEN}'
  script:
  - npm publish


Node:
  stage: Build
  artifacts:
    paths:
    - ./build
  before_script:
  - npm ci
  script:
  - npm run build

NPM:
  extends: .deploy
  variables:
    REGISTRY: registry.npmjs.org
    TOKEN: ${NPM_TOKEN}
GitLab:
  extends: .deploy
  variables:
    REGISTRY: gitlab.com/api/v4/packages/npm
    TOKEN: ${CI_JOB_TOKEN}
GitHub:
  extends: .deploy
  variables:
    REGISTRY: npm.pkg.github.com
    TOKEN: ${GITHUB_TOKEN}
