# https://docs.gitlab.com/ee/ci/yaml
# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
variables:
  CODEBERG_USERNAME: tinnedtea

image: node:16-bullseye-slim
stages:
- Build
- Deploy
workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    #
    #   The GitLab-if-syntax is extremely confusing. Only one of
    #   the specified if-statements has to match for the rule-
    #   block to succeed. This behaviour can only be mitigated by
    #   supplying 'when: never', which then gets overwriten to
    #   'when: on_success' by following successful if-statements.
    #
    when: never
  - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/

.deploy:
  stage: Deploy
  needs:
  - TypeScript
  before_script:
  - npm config set \
      access public \
      registry "https://${REGISTRY}/" \
      "//${REGISTRY}/:_authToken" '${TOKEN}'
  script:
  - npm publish


TypeScript:
  stage: Build
  artifacts:
    paths:
    - ./build
  before_script:
  - npm ci
  script:
  - npm run build

Codeberg:
  extends:
  - .deploy
  variables:
    REGISTRY: codeberg.org/api/packages/${CODEBERG_USERNAME}/npm
    TOKEN: $CODEBERG_TOKEN
GitLab:
  extends:
  - .deploy
  variables:
    REGISTRY: gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm
    TOKEN: $CI_JOB_TOKEN
GitHub:
  extends:
  - .deploy
  variables:
    REGISTRY: npm.pkg.github.com
    TOKEN: $GITHUB_TOKEN
NPM:
  extends:
  - .deploy
  variables:
    REGISTRY: registry.npmjs.org
    TOKEN: $NPM_TOKEN
