import { isElement as matchNode } from 'hast-util-is-element'
import { toString as stringifyNode } from 'hast-util-to-string'
import { visit as walkTree } from 'unist-util-visit'

/**
	@typedef Config

	@property { boolean } [overwrite]
	Defines if existing ids should be overwritten.

	@property { (textContent: string) => string } slugger
	Function which generates the desired slug.
	This plugin handles duplicate ids in
	{@link Config.uniqueifier | `uniqueifier`},
	so there is no need for a fancy object
	wrapper here.

	@property { import('hast-util-is-element').Test } [test]
	[`Test`](https://github.com/syntax-tree/hast-util-is-element#function-testelement-index-parent)
	which marks rehype-nodes as sluggable. Defaults
	to heading nodes.

	@property { (slug: string, instance: number, textContent: string) => string } [uniqueifier]
	Function which makes a slug more unique. It
	only gets called if a generated slug (including
	the ones generated by this function) turns out
	to be a duplicate.
*/


/**
	Add customisable ids to your [`rehype`](https://github.com/rehypejs/rehype)-nodes.

	@example
	import { rehype } from 'rehype'
	import slug from '@tinnedtea/rehype-slug'

	await rehype()
		.use(slug, () => String(Math.random()))
		.process('<h1/>')
	// returns '<h1 id="0.69..."/>'

	@type { import('unified').Plugin<(Config | Config['slugger'])[], import('hast').Root> }
*/
export function slug(input) {
	if (!input) {
		throw new Error('No slug-generator provided, exiting. @tinnedtea/rehype-slug does not provide a default.')
	}

	/** @type { Config } */
	const config = typeof input === 'object' ? input : { slugger: input }


	return tree => {
		if (!config.test) {
			config.test = function(node) {
				return /^h[1-6]$/.test(node.tagName)
			}
		}
		if (!config.uniqueifier) {
			config.uniqueifier = function(slug, instance) {
				return `${ slug }-${ instance }`
			}
		}

		/** @type { Set<string> } */
		const ids = new Set()
		/** @type { Set<import('hast').Element> } */
		const nodes = new Set()

		walkTree(tree, 'element', node => {
			if (!config.overwrite && node.properties?.id) {
				ids.add(String(node.properties.id))
			}
			if (matchNode(node, config.test)) {
				nodes.add(node)
			}
		})

		for (const node of nodes) {
			if (config.overwrite || !node.properties?.id) {
				const textContent = stringifyNode(node)
				const slug = config.slugger(textContent)

				let id = slug
				for (let instance = 2; ids.has(id); instance++) {
					id = config.uniqueifier(slug, instance, textContent)
				}

				ids.add(id)
				node.properties = {
					...node.properties,
					id
				}
			}
		}
	}
}

export default slug
